# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id_code',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.CharField(db_index=True, max_length=13, primary_key=True, serialize=False, unique=True),
        ),
    ]
