# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_auto_20171210_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='scan',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/%d'),
        ),
    ]
