# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-29 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_auto_20171220_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.Category'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='scan',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, size=[500, 500], upload_to='receipts/%Y/%m/%d'),
        ),
    ]
